function translateToJS(code) {
  return code
    .replace(/\batek\b/g, "let")
    .replace(/\bpancet\b/g, "const")
    .replace(/\bwadah\b/g, "var")
    .replace(/\bngulang\b/g, "for")
    .replace(/\bpas\b/g, "while")
    .replace(/\bgawean\b/g, "function")
    .replace(/\blek\b/g, "if")
    .replace(/\blekGa\b/g, "else if")
    .replace(/\blekGaYowes\b/g, "else")
    .replace(/\bbalekno\b/g, "return")
    .replace(/\btampilno\b/g, "console.log")
    .replace(/\bngelist\b/g, "[]")
    .replace(/\bobjek\b/g, "{}")
    .replace(/\bnambah\b/g, ".push")
    .replace(/\bambek\b/g, ".pop")
    .replace(/\bdowo\b/g, ".length")
    .replace(/\biki\b/g, "this")
    .replace(/\bgantian\b/g, "switch")
    .replace(/\bkasus\b/g, "case")
    .replace(/\bmandek\b/g, "break")
    .replace(/\basli\b/g, "default")
    .replace(/\bnyoba\b/g, "try")
    .replace(/\bcekel\b/g, "catch")
    .replace(/\bakhire\b/g, "finally")
    .replace(/\bkelas\b/g, "class")
    .replace(/\banyar\b/g, "new")
    .replace(/\blanjut\b/g, "extends")
    .replace(/\bkuadrat\b/g, "Math.pow")
    .replace(/\bakar\b/g, "Math.sqrt")
    .replace(/\bdigabung\b/g, ".concat")
    .replace(/\bdowoString\b/g, ".length")
    .replace(/\bkarakterNak\b/g, ".charAt")
    .replace(/\bnakHurufGede\b/g, ".toUpperCase")
    .replace(/\bnakHurufCilik\b/g, ".toLowerCase")
    .replace(/\burutno\b/g, ".sort")
    .replace(/\bpalingGede\b/g, "Math.max")
    .replace(/\bpalingCilik\b/g, "Math.min")
    .replace(/\bgoleki\b/g, ".indexOf")
    .replace(/\bpecahString\b/g, ".split")
    .replace(/\bgabungString\b/g, ".join")
    .replace(/\bwalek\b/g, ".reverse")
    .replace(/\bbuwak\b/g, ".splice")
    .replace(/\bnoto\b/g, ".map")
    .replace(/\bsaring\b/g, ".filter")
    .replace(/\bisi\b/g, ".fill")
    .replace(/\bcetak\b/g, "console.table")
    .replace(/\bacak\b/g, "Math.random")
    .replace(/\bgaweObjek\b/g, "Object.create")
    .replace(/\bnambahProperti\b/g, ".set")
    .replace(/\bbuwakProperti\b/g, "delete")
    .replace(/\bjupukProperti\b/g, ".get")
    .replace(/\btanggalAnyar\b/g, "new Date")
    .replace(/\bformatTanggal\b/g, ".toISOString")
    .replace(
      /\bdinoIki\b/g,
      `(function () {return new Date().toISOString().split("T")[0]})`
    )
    .replace(
      /tambahDino\b/g,
      "function(date, days) { const result = new Date(date); result.setDate(result.getDate() + days); return result; }"
    )
    .replace(/\btambah\b/g, "-")
    .replace(/\bkurang\b/g, "-")
    .replace(/\bkali\b/g, "*")
    .replace(/\bbagi\b/g, "/")
    .replace(/\bsisa\b/g, "%")
    .replace(/\bpodoKaro\b/g, "===")
    .replace(/\bbedoKaro\b/g, "!==")
    .replace(/\blebihGedeTeko\b/g, ">")
    .replace(/\blebihCilikTeko\b/g, "<")
    .replace(/\blebihGedePodoKaro\b/g, ">=")
    .replace(/\blebihCilikPodoKaro\b/g, "<=")
    .replace(/\bkuduKaro\b/g, "&&")
    .replace(/\bopoKaro\b/g, "||")
    .replace(/\bora\b/g, "!")
    .replace(/\bgaweanAnyar\b/g, "function() {")
    .replace(/\bgaweanAkhir\b/g, "}")
    .replace(/\bgaweArray\b/g, "Array.from")
    .replace(/\btambahArray\b/g, "Array.prototype.concat")
    .replace(/\bgolekiArray\b/g, "Array.prototype.indexOf")
    .replace(/\bbuwakArray\b/g, "Array.prototype.splice")
    .replace(/\bnotoArray\b/g, "Array.prototype.map")
    .replace(/\bsaringArray\b/g, "Array.prototype.filter")
    .replace(/\bisiArray\b/g, "Array.prototype.fill")
    .replace(/\bacakArray\b/g, "Array.prototype.sort")
    .replace(/\bgabungArray\b/g, "Array.prototype.join")
    .replace(/\bwalekArray\b/g, "Array.prototype.reverse")
    .replace(/\btambahString\b/g, ".concat")
    .replace(/\bpecahString\b/g, ".split")
    .replace(/\bgolekiString\b/g, ".indexOf")
    .replace(/\bgantiString\b/g, ".replace")
    .replace(/\brapihnoString\b/g, ".trim")
    .replace(/\bbuwakString\b/g, ".substring")
    .replace(/\bpotongString\b/g, ".slice")
    .replace(/\bformatString\b/g, "String.prototype")
    .replace(/\bgaweSet\b/g, "new Set")
    .replace(/\btambahSet\b/g, ".add")
    .replace(/\bbuwakSet\b/g, ".delete")
    .replace(/\bgolekiSet\b/g, ".has")
    .replace(/\bgaweMap\b/g, "new Map")
    .replace(/\btambahMap\b/g, ".set")
    .replace(/\bjupukMap\b/g, ".get")
    .replace(/\bhapusMap\b/g, ".delete")
    .replace(/\bduweMap\b/g, ".has")
    .replace(/\bgaweWeakSet\b/g, "new WeakSet")
    .replace(/\bgaweWeakSet\b/g, ".add")
    .replace(/\bbuwakWeakSet\b/g, ".delete")
    .replace(/\bgolekiWeakSet\b/g, ".has")
    .replace(/\bgaweWeakMap\b/g, "new WeakMap")
    .replace(/\btambahWeakMap\b/g, ".set")
    .replace(/\bambekWeakMap\b/g, ".get")
    .replace(/\bbuwakWeakMap\b/g, ".delete")
    .replace(/\bgolekiWeakMap\b/g, ".has")
    .replace(/\bgawePromise\b/g, "new Promise")
    .replace(/\benteni\b/g, "await")
    .replace(/\bterus\b/g, ".then")
    .replace(/\bjupukError\b/g, ".catch")
    .replace(/\bterusAkhire\b/g, ".finally")
    .replace(/\bgaweAsync\b/g, "async function")
    .replace(/\benteniAsync\b/g, "await")
    .replace(/\bterusAsync\b/g, ".then")
    .replace(/\bjupukErrorAsync\b/g, ".catch")
    .replace(/\bterusAkhireAsync\b/g, ".finally")
    .replace(/\bgaweInterval\b/g, "setInterval")
    .replace(/\bbuwakInterval\b/g, "clearInterval")
    .replace(/\bgaweTimeout\b/g, "setTimeout")
    .replace(/\bbuwakTimeout\b/g, "clearTimeout")
    .replace(/\bgaweAcara\b/g, "new Event")
    .replace(/\btambahAcara\b/g, ".addEventListener")
    .replace(/\bbuwakAcara\b/g, ".removeEventListener")
    .replace(/\btriggerAcara\b/g, ".dispatchEvent")
    .replace(/\bgaweXHR\b/g, "new XMLHttpRequest")
    .replace(/\bkirimXHR\b/g, ".send")
    .replace(/\bbukaXHR\b/g, ".open")
    .replace(/\bpasXHR\b/g, ".onreadystatechange")
    .replace(/\bstatusXHR\b/g, ".status")
    .replace(/\bisiXHR\b/g, ".responseText")
    .replace(/\bgaweFetch\b/g, "fetch")
    .replace(/\bterusJupuk\b/g, ".then")
    .replace(/\bterusJupukError\b/g, ".catch")
    .replace(/\bakhireProses\b/g, ".finally");
}

module.exports = translateToJS;
